language: ruby
rvm:
- 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
branches:
  only:
  - master
install:
- bundle install
script:
- bundle exec jekyll build
- timeout 240s bundle exec htmlproofer ./_site --check-html --check-favicon --allow-hash-href
  --external_only --only-4xx --http-status-ignore 429
after_success: s3_website push
notifications:
  slack:
    rooms:
      - secure: i+mniaGtY5pdggb9CbPYpi3OOX9wuuFYtwGhR6KsAJ3U82eCb7SgAHpBn31jAJVg4wrtFv+zfe/9KRoYsh4gezwjHS4eNlc2+6fMji25SaDfeDIDI0TqZcJfwkoJaCRFGgDwzXKZT8XuGxNQp50Z2fyFIWM5StPo8c9yhoTwJUiS5RuQP5KJJS9nvMV5iYI7iLOQGtGUtHFb+6bdaSOs4pdzMmE++CEcbeNL9jE+YEeYLvUXayFezUdgEy5+1/iTmJdz57r+MXinG5SRAlVAl6We7SmMiejA6bp8KhhSrwB2h9ObhPlue9EktdWuVKLcoA0950ndz4BNM7aWJ5WvAIRgdTV2IRUhc+gqvzLsgdCpIhdPo4aKhSvp1w+SRvlLJWLKmuSRpdmbpc7wHnJ+2f4T0oNTNqp92mFmki8d/RT/lAC/nDJYz7E8ndJU3AFJ0zwC0ro291GknovXOMHh979EXwt7vBnNgn5eufCpgrMQLoh9SQYLvgYLA0rAl4f7JHzr07PilRvUYclV7bV9frMLUvaEUPCJXmU2JOUagp6xTPtX7+teNTHS247TVePhfxB1pfC3giSAiXZCwNeKBmnHDJgHcGN0pdAEWc7CoOrYolAEt6gNV7sgZZX0/OlrzymmhBkFQ/qccTPkZ6x0TuWYcpe3jLHGY7G8ZWzlNeA=
    on_success: always
